CREATE TABLE IF NOT EXISTS api_token (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
    token_hash      VARCHAR(64) NOT NULL,
    user_id         BIGINT NOT NULL,
    mandat          VARCHAR(255),
    description     VARCHAR(100),
    token_name      VARCHAR(100),
    user_email      VARCHAR(255),
    invalidated     BOOLEAN DEFAULT FALSE NOT NULL,
    expires_at      TIMESTAMP,
    last_used_at    TIMESTAMP,
    use_count       BIGINT DEFAULT 0 NOT NULL,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    tags            VARCHAR(5000),
    deleted         BOOLEAN DEFAULT FALSE,
    created_by      VARCHAR(255),
    created_date    TIMESTAMP,
    last_modified_by    VARCHAR(255),
    last_modified_date  TIMESTAMP,
    CONSTRAINT uk_api_token_hash UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS idx_api_token_user_mandat ON api_token (user_id, mandat);
CREATE INDEX IF NOT EXISTS idx_api_token_hash ON api_token (token_hash);
