-- i18n translation table for menu labels and UI texts
CREATE TABLE IF NOT EXISTS i18n_translation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    default_label   VARCHAR(500) NOT NULL,
    language_code   VARCHAR(10)  NOT NULL,
    translated_text VARCHAR(500) NOT NULL,
    CONSTRAINT uq_i18n_label_lang UNIQUE (default_label, language_code)
);
