name: Build & Deploy

on:
  push:
    branches: [master]

concurrency:
  group: plaintext-root-build
  cancel-in-progress: false

jobs:
  build:
    uses: daniel-marthaler/plaintext-scripts/.github/workflows/maven-build-deploy.yaml@master
    with:
      build-command: "5"
    secrets: inherit
