name: Build & Deploy

on:
  push:
    branches: [master]

concurrency:
  group: plaintext-root
  cancel-in-progress: false

jobs:
  build:
    uses: daniel-marthaler/plaintext-scripts/.github/workflows/maven-build-deploy.yaml@master
    secrets:
      TWINGATE_SERVICE_KEY: ${{ secrets.TWINGATE_SERVICE_KEY }}
